### ISSUE TITLE
你好，关于DataApi这个块的配置不是很明白。

### ISSUE THREAD

**Issue by lisgking** [Bacra/node-d2server#11]
你好，关于DataApi这个块的配置不是很明白。
能给个例子示范一下吗？谢谢

**Comment by Bacra** [comment]
不好意思，很久之前写的，找不到实例
项目已经不更新了，可以使用百度的fis替换

DataApi的配置可以参考，作用是将现网的动态数据，落地到本地文件，下次访问直接使用本地文件 (可以直接修改本地文件模拟数据)
http://bacra.github.io/node-d2server/v3.2.3/module.html
